services:
  app:
    build: .
    container_name: team-manage-app
    expose:
      - '${APP_PORT:-8008}'
    volumes:
      - './data:/app/data'
    restart: always
    environment:
      - APP_PORT=${APP_PORT:-8008}
      - HOST=0.0.0.0
      - DATABASE_URL=sqlite+aiosqlite:////app/data/team_manage.db
